import { AthleteProfile, CombatProfile, ExerciseCategory, ExerciseLibraryItem } from "../types";

type ExerciseLibraryInput = Omit<ExerciseLibraryItem, "contraindications"> & {
  contraindications?: string[];
};

export const exerciseLibrary: ExerciseLibraryItem[] = [
  ex({
    id: "dynamic-mobility-flow",
    nameEn: "Dynamic Mobility Flow",
    nameUa: "Динамічна мобільність",
    category: "warmup",
    combatProfiles: ["all"],
    pattern: "mobility",
    bodyRegions: ["hip", "t-spine", "ankle"],
    equipment: ["Bodyweight", "Mat Only"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "1",
    defaultReps: "6 min",
    defaultTempo: "-",
    defaultRest: "-",
    defaultIntensity: "RPE 3",
    notesUa: "Плавно відкрий таз, грудний відділ і гомілкостоп.",
    notesEn: "Open hips, T-spine, and ankles smoothly.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "scap-pushup-neck-prep",
    nameEn: "Scap Push-Up + Neck Prep",
    category: "warmup",
    combatProfiles: ["grappler", "hybrid"],
    pattern: "isometric",
    bodyRegions: ["shoulder", "neck"],
    equipment: ["Mat Only"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "2",
    defaultReps: "8 + 15s",
    defaultTempo: "controlled",
    defaultRest: "30s",
    defaultIntensity: "Easy",
    notesUa: "Підготуй плечі і шию до контакту.",
    notesEn: "Prepare shoulders and neck for contact.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "low-pogo-hip-switch",
    nameEn: "Low Pogo + Hip Switch",
    category: "warmup",
    combatProfiles: ["striker", "hybrid"],
    pattern: "jump",
    bodyRegions: ["ankle", "hip"],
    equipment: ["Bodyweight"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "2",
    defaultReps: "20 + 6/side",
    defaultTempo: "quick",
    defaultRest: "30s",
    defaultIntensity: "Easy",
    notesUa: "Пружність стопи без втоми.",
    notesEn: "Build foot stiffness without fatigue.",
    sourceReference: "OTA-inspired",
  }),
  ex({
    id: "box-jump",
    nameEn: "Box Jump",
    category: "power",
    combatProfiles: ["grappler", "hybrid"],
    pattern: "jump",
    bodyRegions: ["lower"],
    equipment: ["Box"],
    level: "intermediate",
    phases: ["accumulation", "transmutation", "realization"],
    defaultSets: "3-5",
    defaultReps: "3",
    defaultTempo: "X",
    defaultRest: "90s",
    defaultIntensity: "Crisp",
    notesUa: "Зупиняй сет до втрати швидкості.",
    notesEn: "Stop the set before speed drops.",
    sourceReference: "OTA-inspired",
  }),
  ex({
    id: "acceleration-build-up",
    nameEn: "Acceleration Build-Up",
    category: "speed",
    combatProfiles: ["striker", "hybrid"],
    pattern: "sprint",
    bodyRegions: ["lower"],
    equipment: ["Open Space"],
    level: "intermediate",
    phases: ["accumulation", "transmutation", "realization"],
    defaultSets: "3-5",
    defaultReps: "10m",
    defaultTempo: "X",
    defaultRest: "90s",
    defaultIntensity: "Crisp",
    notesUa: "Зупиняй сет до втрати швидкості.",
    notesEn: "Stop the set before speed drops.",
    sourceReference: "OTA-inspired",
  }),
  ex({
    id: "broad-jump",
    nameEn: "Broad Jump",
    category: "power",
    combatProfiles: ["grappler", "hybrid", "striker"],
    pattern: "jump",
    bodyRegions: ["lower"],
    equipment: ["Open Space"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "3-5",
    defaultReps: "3",
    defaultTempo: "X",
    defaultRest: "90s",
    defaultIntensity: "High quality",
    notesUa: "Повний відпочинок, кожен стрибок якісний.",
    notesEn: "Full rest, every jump high quality.",
    sourceReference: "OTA-inspired",
  }),
  ex({
    id: "lateral-bound",
    nameEn: "Lateral Bound",
    category: "power",
    combatProfiles: ["striker", "hybrid"],
    pattern: "jump",
    bodyRegions: ["lower", "ankle", "knee"],
    equipment: ["Open Space"],
    level: "intermediate",
    phases: ["all"],
    defaultSets: "3-5",
    defaultReps: "3/side",
    defaultTempo: "X",
    defaultRest: "75-90s",
    defaultIntensity: "High quality",
    notesUa: "Контролюй приземлення і коліно.",
    notesEn: "Control landing and knee position.",
    sourceReference: "OTA-inspired",
  }),
  ex({
    id: "med-ball-rotational-throw",
    nameEn: "Med Ball Rotational Throw",
    category: "power",
    combatProfiles: ["striker", "hybrid"],
    pattern: "rotation",
    bodyRegions: ["trunk", "hip", "shoulder"],
    equipment: ["Med Balls"],
    level: "intermediate",
    phases: ["transmutation", "realization", "all"],
    defaultSets: "3-5",
    defaultReps: "4/side",
    defaultTempo: "X",
    defaultRest: "60-90s",
    defaultIntensity: "Max speed",
    notesUa: "Ротація швидка, не силова мʼясорубка.",
    notesEn: "Fast rotation, not a grinding strength rep.",
    sourceReference: "OTA-inspired",
  }),
  ex({
    id: "med-ball-chest-pass",
    nameEn: "Med Ball Chest Pass",
    category: "power",
    combatProfiles: ["grappler", "hybrid", "striker"],
    pattern: "throw",
    bodyRegions: ["upper", "trunk"],
    equipment: ["Med Balls"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "3-5",
    defaultReps: "4",
    defaultTempo: "X",
    defaultRest: "60-90s",
    defaultIntensity: "Max speed",
    notesUa: "Вибух без втрати позиції ребер.",
    notesEn: "Explode without losing rib position.",
    sourceReference: "OTA-inspired",
  }),
  ex({
    id: "trap-bar-deadlift",
    nameEn: "Trap Bar Deadlift",
    category: "strength",
    combatProfiles: ["grappler", "hybrid"],
    pattern: "hinge",
    bodyRegions: ["posterior chain", "trunk"],
    equipment: ["Barbell", "Trap Bar"],
    level: "intermediate",
    phases: ["accumulation", "transmutation"],
    defaultSets: "4",
    defaultReps: "3-5",
    defaultTempo: "2-1-X-1",
    defaultRest: "2-3 min",
    defaultIntensity: "RPE 7-8",
    contraindications: ["Lower Back"],
    notesUa: "Сильний brace, не добивай поперек.",
    notesEn: "Strong brace, do not crush the low back.",
    sourceReference: "OTA-inspired",
  }),
  ex({
    id: "front-squat",
    nameEn: "Front Squat",
    category: "strength",
    combatProfiles: ["striker", "grappler", "hybrid"],
    pattern: "squat",
    bodyRegions: ["lower", "trunk"],
    equipment: ["Barbell"],
    level: "intermediate",
    phases: ["accumulation", "transmutation"],
    defaultSets: "4",
    defaultReps: "4-5",
    defaultTempo: "3-1-X-1",
    defaultRest: "2-3 min",
    defaultIntensity: "RPE 7",
    contraindications: ["Knee", "Lower Back"],
    notesUa: "Сила ніг без забивання перед спарингом.",
    notesEn: "Leg strength without crushing sparring readiness.",
    sourceReference: "OTA-inspired",
  }),
  ex({
    id: "goblet-squat",
    nameEn: "Goblet Squat",
    category: "strength",
    combatProfiles: ["striker", "grappler", "hybrid"],
    pattern: "squat",
    bodyRegions: ["lower", "trunk"],
    equipment: ["Dumbbells", "Kettlebells"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "3",
    defaultReps: "6-8",
    defaultTempo: "3-1-X-1",
    defaultRest: "90s",
    defaultIntensity: "2 RIR",
    contraindications: ["Knee", "Lower Back"],
    notesUa: "Використовуй, коли штанга недоступна або зараз недоречна.",
    notesEn: "Use this when barbell loading is not available or not appropriate.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "rear-foot-elevated-split-squat",
    nameEn: "Rear Foot Elevated Split Squat",
    category: "strength",
    combatProfiles: ["striker", "hybrid"],
    pattern: "squat",
    bodyRegions: ["lower", "hip", "knee"],
    equipment: ["Dumbbells", "Bodyweight"],
    level: "intermediate",
    phases: ["all"],
    defaultSets: "3",
    defaultReps: "6/side",
    defaultTempo: "3-1-X-1",
    defaultRest: "90s",
    defaultIntensity: "2 RIR",
    contraindications: ["Knee"],
    notesUa: "Тримай стопу і коліно стабільно.",
    notesEn: "Keep foot and knee stable.",
    sourceReference: "OTA-inspired",
  }),
  ex({
    id: "weighted-chin-up",
    nameEn: "Weighted Chin-Up",
    category: "strength",
    combatProfiles: ["grappler", "hybrid"],
    pattern: "pull",
    bodyRegions: ["upper", "grip"],
    equipment: ["Pull-up Bar"],
    level: "advanced",
    phases: ["accumulation", "transmutation"],
    defaultSets: "3",
    defaultReps: "4-6",
    defaultTempo: "2-1-X-1",
    defaultRest: "2 min",
    defaultIntensity: "RPE 7",
    contraindications: ["Elbow/Wrist/Hand", "Shoulder"],
    notesUa: "Сильна тяга, але не вбивай хват перед боротьбою.",
    notesEn: "Strong pull, but do not bury grip before wrestling.",
    sourceReference: "OTA-inspired",
  }),
  ex({
    id: "push-up",
    nameEn: "Push-Up",
    category: "strength",
    combatProfiles: ["striker", "grappler", "hybrid"],
    pattern: "push",
    bodyRegions: ["upper", "trunk"],
    equipment: ["Bodyweight", "Mat Only"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "3",
    defaultReps: "6-12",
    defaultTempo: "3-1-X-1",
    defaultRest: "75s",
    defaultIntensity: "2 RIR",
    contraindications: ["Shoulder", "Elbow/Wrist/Hand"],
    notesUa: "Ребра вниз, плече рухається чисто.",
    notesEn: "Keep ribs down and shoulder path clean.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "shoulder-isometric-reset",
    nameEn: "Shoulder Isometric Reset",
    category: "prehab",
    combatProfiles: ["striker", "hybrid", "grappler"],
    pattern: "isometric",
    bodyRegions: ["shoulder", "scap"],
    equipment: ["Bodyweight", "Bands"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "2",
    defaultReps: "20s/position",
    defaultTempo: "ISO",
    defaultRest: "30s",
    defaultIntensity: "Pain-free",
    notesUa: "Тільки без болю: легкий тиск, чиста позиція лопатки.",
    notesEn: "Pain-free only: light pressure, clean scapular position.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "landmine-press",
    nameEn: "Landmine Press",
    category: "strength",
    combatProfiles: ["striker", "hybrid"],
    pattern: "push",
    bodyRegions: ["shoulder", "trunk"],
    equipment: ["Barbell"],
    level: "intermediate",
    phases: ["all"],
    defaultSets: "3",
    defaultReps: "6/side",
    defaultTempo: "2-0-X-1",
    defaultRest: "90s",
    defaultIntensity: "RPE 7",
    contraindications: ["Shoulder"],
    notesUa: "Плече рухається чисто, ребра вниз.",
    notesEn: "Clean shoulder path, ribs down.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "farmer-carry",
    nameEn: "Farmer Carry",
    category: "accessory",
    combatProfiles: ["grappler", "hybrid"],
    pattern: "carry",
    bodyRegions: ["grip", "trunk", "shoulder"],
    equipment: ["Dumbbells", "Kettlebells"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "3",
    defaultReps: "30m",
    defaultTempo: "-",
    defaultRest: "90s",
    defaultIntensity: "Heavy but clean",
    contraindications: ["Elbow/Wrist/Hand", "Shoulder"],
    notesUa: "Хват і корпус, без перекосу.",
    notesEn: "Grip and trunk without leaning.",
    sourceReference: "Daru-inspired",
  }),
  ex({
    id: "pallof-press",
    nameEn: "Pallof Press",
    category: "accessory",
    combatProfiles: ["striker", "hybrid", "grappler"],
    pattern: "anti_rotation",
    bodyRegions: ["trunk"],
    equipment: ["Bands", "Cable"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "3",
    defaultReps: "10/side",
    defaultTempo: "2-1-2-1",
    defaultRest: "45s",
    defaultIntensity: "Smooth",
    notesUa: "Не крути корпус.",
    notesEn: "Do not rotate the trunk.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "sled-push",
    nameEn: "Sled Push",
    category: "accessory",
    combatProfiles: ["hybrid", "grappler"],
    pattern: "conditioning",
    bodyRegions: ["lower", "trunk"],
    equipment: ["Sled"],
    level: "intermediate",
    phases: ["all"],
    defaultSets: "3",
    defaultReps: "20m",
    defaultTempo: "-",
    defaultRest: "90s",
    defaultIntensity: "Hard",
    notesUa: "Потужно, але без відмови.",
    notesEn: "Powerful, but not to failure.",
    sourceReference: "Daru-inspired",
  }),
  ex({
    id: "zone-2-bike",
    nameEn: "Zone 2 Bike",
    category: "conditioning",
    combatProfiles: ["all"],
    pattern: "conditioning",
    bodyRegions: ["cardio"],
    equipment: ["Bike"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "1",
    defaultReps: "25-35 min",
    defaultTempo: "-",
    defaultRest: "-",
    defaultIntensity: "HR Zone 2",
    notesUa: "Ніс/легке дихання, без закислення.",
    notesEn: "Easy nasal or controlled breathing, no burn.",
    sourceReference: "Daru-inspired",
  }),
  ex({
    id: "assault-bike-repeated-efforts",
    nameEn: "Assault Bike Repeated Efforts",
    category: "conditioning",
    combatProfiles: ["grappler", "hybrid"],
    pattern: "conditioning",
    bodyRegions: ["cardio"],
    equipment: ["Bike"],
    level: "intermediate",
    phases: ["transmutation", "realization"],
    defaultSets: "6",
    defaultReps: "15s",
    defaultTempo: "-",
    defaultRest: "75s",
    defaultIntensity: "RPE 8",
    notesUa: "Імітація повторних вибухів без техніки боротьби.",
    notesEn: "Repeat bursts without adding grappling skill fatigue.",
    sourceReference: "Daru-inspired",
  }),
  ex({
    id: "tempo-runs-or-bike",
    nameEn: "Tempo Runs or Bike",
    category: "conditioning",
    combatProfiles: ["striker", "hybrid"],
    pattern: "conditioning",
    bodyRegions: ["cardio"],
    equipment: ["Open Space", "Bike", "Treadmill"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "8",
    defaultReps: "30s",
    defaultTempo: "-",
    defaultRest: "60s",
    defaultIntensity: "Zone 3-4",
    notesUa: "Ритм раунду, не максимум.",
    notesEn: "Round rhythm, not max effort.",
    sourceReference: "Daru-inspired",
  }),
  ex({
    id: "neck-isometric-series",
    nameEn: "Neck Isometric Series",
    category: "prehab",
    combatProfiles: ["grappler", "hybrid", "striker"],
    pattern: "isometric",
    bodyRegions: ["neck"],
    equipment: ["Bodyweight"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "2",
    defaultReps: "15s each",
    defaultTempo: "ISO",
    defaultRest: "30s",
    defaultIntensity: "Easy",
    contraindications: ["Neck", "Concussion History"],
    notesUa: "Без болю і без різких рухів.",
    notesEn: "No pain and no jerky motion.",
    sourceReference: "Daru-inspired",
  }),
  ex({
    id: "copenhagen-plank",
    nameEn: "Copenhagen Plank",
    category: "prehab",
    combatProfiles: ["grappler", "hybrid", "striker"],
    pattern: "isometric",
    bodyRegions: ["adductor", "hip", "knee"],
    equipment: ["Bench", "Mat Only"],
    level: "intermediate",
    phases: ["all"],
    defaultSets: "2",
    defaultReps: "20s/side",
    defaultTempo: "ISO",
    defaultRest: "45s",
    defaultIntensity: "Clean",
    contraindications: ["Hip", "Knee"],
    notesUa: "Профілактика паху/коліна.",
    notesEn: "Groin/knee prevention.",
    sourceReference: "Daru-inspired",
  }),
  ex({
    id: "calf-isometric-hold",
    nameEn: "Calf Isometric Hold",
    category: "prehab",
    combatProfiles: ["striker", "hybrid"],
    pattern: "isometric",
    bodyRegions: ["ankle", "calf"],
    equipment: ["Bodyweight"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "2",
    defaultReps: "30s",
    defaultTempo: "ISO",
    defaultRest: "45s",
    defaultIntensity: "Moderate",
    contraindications: ["Ankle/Foot"],
    notesUa: "Стопа жорстка, але без судоми.",
    notesEn: "Foot stiff, but no cramping.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "band-external-rotation",
    nameEn: "Band External Rotation",
    category: "prehab",
    combatProfiles: ["striker", "hybrid", "grappler"],
    pattern: "pull",
    bodyRegions: ["shoulder", "scap"],
    equipment: ["Bands"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "2",
    defaultReps: "12/side",
    defaultTempo: "2-1-2-1",
    defaultRest: "30s",
    defaultIntensity: "Easy",
    contraindications: ["Shoulder"],
    notesUa: "Лопатка стабільна.",
    notesEn: "Scapula stays stable.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "dead-bug",
    nameEn: "Dead Bug",
    category: "prehab",
    combatProfiles: ["hybrid", "striker", "grappler"],
    pattern: "anti_rotation",
    bodyRegions: ["trunk"],
    equipment: ["Mat Only"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "2",
    defaultReps: "8/side",
    defaultTempo: "controlled",
    defaultRest: "30s",
    defaultIntensity: "Clean",
    notesUa: "Ребра вниз, таз стабільний.",
    notesEn: "Ribs down, pelvis stable.",
    sourceReference: "Black Bear",
  }),
];

export function findExercise(id: string) {
  const exercise = exerciseLibrary.find((item) => item.id === id);
  if (!exercise) throw new Error(`Missing exercise: ${id}`);
  return exercise;
}

export function prescribeExercise(
  id: string,
  overrides: Partial<Pick<ExerciseLibraryItem, "defaultSets" | "defaultReps" | "defaultTempo" | "defaultRest" | "defaultIntensity">> = {},
) {
  const exercise = findExercise(id);
  return {
    name: exercise.nameEn,
    sets: overrides.defaultSets ?? exercise.defaultSets,
    reps: overrides.defaultReps ?? exercise.defaultReps,
    tempo: overrides.defaultTempo ?? exercise.defaultTempo,
    rest: overrides.defaultRest ?? exercise.defaultRest,
    intensity: overrides.defaultIntensity ?? exercise.defaultIntensity,
    notesUa: exercise.notesUa,
    notesEn: exercise.notesEn,
  };
}

export function prescribeBestExercise(
  ids: string[],
  athleteProfile: AthleteProfile,
  overrides: Partial<Pick<ExerciseLibraryItem, "defaultSets" | "defaultReps" | "defaultTempo" | "defaultRest" | "defaultIntensity">> = {},
) {
  const preferred = ids.map(findExercise);
  const available = preferred.filter((exercise) => isExerciseAvailable(exercise, athleteProfile));
  const safeAvailable = available.filter((exercise) => !hasRiskConflict(exercise, athleteProfile));
  const selected = safeAvailable[0] ?? available[0] ?? preferred[0];
  const prescription = prescribeExercise(selected.id, overrides);
  const conflicts = getRiskConflicts(selected, athleteProfile);

  if (conflicts.length) {
    const warningUa = `Ризик: ${conflicts.join(", ")}. Працюй тільки без болю, зменши амплітуду або заміни вправу.`;
    const warningEn = `Risk flag: ${conflicts.join(", ")}. Keep it pain-free, reduce range, or replace the exercise.`;
    return {
      ...prescription,
      notesUa: [prescription.notesUa, warningUa].filter(Boolean).join(" "),
      notesEn: [prescription.notesEn, warningEn].filter(Boolean).join(" "),
    };
  }

  return prescription;
}

export function filterExercises(category: ExerciseCategory, profile: CombatProfile) {
  return exerciseLibrary.filter(
    (exercise) => exercise.category === category && (exercise.combatProfiles.includes(profile) || exercise.combatProfiles.includes("all")),
  );
}

function isExerciseAvailable(exercise: ExerciseLibraryItem, athleteProfile: AthleteProfile) {
  const alwaysAvailable = ["Bodyweight", "Mat Only", "Open Space"];
  const availableEquipment = new Set([...alwaysAvailable, ...athleteProfile.equipment]);
  return exercise.equipment.some((item) => availableEquipment.has(item));
}

function hasRiskConflict(exercise: ExerciseLibraryItem, athleteProfile: AthleteProfile) {
  return getRiskConflicts(exercise, athleteProfile).length > 0;
}

function getRiskConflicts(exercise: ExerciseLibraryItem, athleteProfile: AthleteProfile) {
  const risks = new Set(athleteProfile.painAreas);
  return exercise.contraindications.filter((risk) => risks.has(risk));
}

function ex(item: ExerciseLibraryInput): ExerciseLibraryItem {
  return {
    contraindications: [],
    ...item,
  };
}
