import { AthleteProfile, CombatProfile, ExerciseCategory, ExerciseLibraryItem } from "../types";
import { getRuleEvidence } from "./methodology";

type ExerciseLibraryInput = Omit<ExerciseLibraryItem, "contraindications"> & {
  contraindications?: string[];
};

export const exerciseLibrary: ExerciseLibraryItem[] = [
  ex({
    id: "dynamic-mobility-flow",
    nameEn: "Dynamic Mobility Flow",
    nameUa: "Динамічна мобільність",
    category: "warmup",
    combatProfiles: ["all"],
    pattern: "mobility",
    bodyRegions: ["hip", "t-spine", "ankle"],
    equipment: ["Bodyweight", "Mat Only"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "1",
    defaultReps: "6 min",
    defaultTempo: "-",
    defaultRest: "-",
    defaultIntensity: "RPE 3",
    notesUa: "Плавно відкрий таз, грудний відділ і гомілкостоп.",
    notesEn: "Open hips, T-spine, and ankles smoothly.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "scap-pushup-neck-prep",
    nameEn: "Scap Push-Up + Neck Prep",
    category: "warmup",
    combatProfiles: ["grappler", "hybrid"],
    pattern: "isometric",
    bodyRegions: ["shoulder", "neck"],
    equipment: ["Mat Only"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "2",
    defaultReps: "8 + 15s",
    defaultTempo: "controlled",
    defaultRest: "30s",
    defaultIntensity: "Easy",
    notesUa: "Підготуй плечі і шию до контакту.",
    notesEn: "Prepare shoulders and neck for contact.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "low-pogo-hip-switch",
    nameEn: "Low Pogo + Hip Switch",
    category: "warmup",
    combatProfiles: ["striker", "hybrid"],
    pattern: "jump",
    bodyRegions: ["ankle", "hip"],
    equipment: ["Bodyweight"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "2",
    defaultReps: "20 + 6/side",
    defaultTempo: "quick",
    defaultRest: "30s",
    defaultIntensity: "Easy",
    notesUa: "Пружність стопи без втоми.",
    notesEn: "Build foot stiffness without fatigue.",
    sourceReference: "OTA-inspired",
  }),
  ex({
    id: "box-jump",
    nameEn: "Box Jump",
    category: "power",
    combatProfiles: ["grappler", "hybrid"],
    pattern: "jump",
    bodyRegions: ["lower"],
    equipment: ["Box"],
    level: "intermediate",
    phases: ["accumulation", "transmutation", "realization"],
    defaultSets: "3-5",
    defaultReps: "3",
    defaultTempo: "X",
    defaultRest: "90s",
    defaultIntensity: "Crisp",
    notesUa: "Зупиняй сет до втрати швидкості.",
    notesEn: "Stop the set before speed drops.",
    sourceReference: "OTA-inspired",
  }),
  ex({
    id: "acceleration-build-up",
    nameEn: "Acceleration Build-Up",
    category: "speed",
    combatProfiles: ["striker", "hybrid"],
    pattern: "sprint",
    bodyRegions: ["lower"],
    equipment: ["Open Space"],
    level: "intermediate",
    phases: ["accumulation", "transmutation", "realization"],
    defaultSets: "3-5",
    defaultReps: "10m",
    defaultTempo: "X",
    defaultRest: "90s",
    defaultIntensity: "Crisp",
    notesUa: "Зупиняй сет до втрати швидкості.",
    notesEn: "Stop the set before speed drops.",
    sourceReference: "OTA-inspired",
  }),
  ex({
    id: "broad-jump",
    nameEn: "Broad Jump",
    category: "power",
    combatProfiles: ["grappler", "hybrid", "striker"],
    pattern: "jump",
    bodyRegions: ["lower"],
    equipment: ["Open Space"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "3-5",
    defaultReps: "3",
    defaultTempo: "X",
    defaultRest: "90s",
    defaultIntensity: "High quality",
    notesUa: "Повний відпочинок, кожен стрибок якісний.",
    notesEn: "Full rest, every jump high quality.",
    sourceReference: "OTA-inspired",
  }),
  ex({
    id: "lateral-bound",
    nameEn: "Lateral Bound",
    category: "power",
    combatProfiles: ["striker", "hybrid"],
    pattern: "jump",
    bodyRegions: ["lower", "ankle", "knee"],
    equipment: ["Open Space"],
    level: "intermediate",
    phases: ["all"],
    defaultSets: "3-5",
    defaultReps: "3/side",
    defaultTempo: "X",
    defaultRest: "75-90s",
    defaultIntensity: "High quality",
    notesUa: "Контролюй приземлення і коліно.",
    notesEn: "Control landing and knee position.",
    sourceReference: "OTA-inspired",
  }),
  ex({
    id: "med-ball-rotational-throw",
    nameEn: "Med Ball Rotational Throw",
    category: "power",
    combatProfiles: ["striker", "hybrid"],
    pattern: "rotation",
    bodyRegions: ["trunk", "hip", "shoulder"],
    equipment: ["Med Balls"],
    level: "intermediate",
    phases: ["transmutation", "realization", "all"],
    defaultSets: "3-5",
    defaultReps: "4/side",
    defaultTempo: "X",
    defaultRest: "60-90s",
    defaultIntensity: "Max speed",
    notesUa: "Ротація швидка, не силова мʼясорубка.",
    notesEn: "Fast rotation, not a grinding strength rep.",
    sourceReference: "OTA-inspired",
  }),
  ex({
    id: "med-ball-chest-pass",
    nameEn: "Med Ball Chest Pass",
    category: "power",
    combatProfiles: ["grappler", "hybrid", "striker"],
    pattern: "throw",
    bodyRegions: ["upper", "trunk"],
    equipment: ["Med Balls"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "3-5",
    defaultReps: "4",
    defaultTempo: "X",
    defaultRest: "60-90s",
    defaultIntensity: "Max speed",
    notesUa: "Вибух без втрати позиції ребер.",
    notesEn: "Explode without losing rib position.",
    sourceReference: "OTA-inspired",
  }),
  ex({
    id: "trap-bar-deadlift",
    nameEn: "Trap Bar Deadlift",
    category: "strength",
    combatProfiles: ["grappler", "hybrid"],
    pattern: "hinge",
    bodyRegions: ["posterior chain", "trunk"],
    equipment: ["Barbell", "Trap Bar"],
    level: "intermediate",
    phases: ["accumulation", "transmutation"],
    defaultSets: "4",
    defaultReps: "3-5",
    defaultTempo: "2-1-X-1",
    defaultRest: "2-3 min",
    defaultIntensity: "RPE 7-8",
    contraindications: ["Lower Back"],
    notesUa: "Сильний brace, не добивай поперек.",
    notesEn: "Strong brace, do not crush the low back.",
    sourceReference: "OTA-inspired",
  }),
  ex({
    id: "front-squat",
    nameEn: "Front Squat",
    category: "strength",
    combatProfiles: ["striker", "grappler", "hybrid"],
    pattern: "squat",
    bodyRegions: ["lower", "trunk"],
    equipment: ["Barbell"],
    level: "intermediate",
    phases: ["accumulation", "transmutation"],
    defaultSets: "4",
    defaultReps: "4-5",
    defaultTempo: "3-1-X-1",
    defaultRest: "2-3 min",
    defaultIntensity: "RPE 7",
    contraindications: ["Knee", "Lower Back"],
    notesUa: "Сила ніг без забивання перед спарингом.",
    notesEn: "Leg strength without crushing sparring readiness.",
    sourceReference: "OTA-inspired",
  }),
  ex({
    id: "goblet-squat",
    nameEn: "Goblet Squat",
    category: "strength",
    combatProfiles: ["striker", "grappler", "hybrid"],
    pattern: "squat",
    bodyRegions: ["lower", "trunk"],
    equipment: ["Dumbbells", "Kettlebells"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "3",
    defaultReps: "6-8",
    defaultTempo: "3-1-X-1",
    defaultRest: "90s",
    defaultIntensity: "2 RIR",
    contraindications: ["Knee", "Lower Back"],
    notesUa: "Використовуй, коли штанга недоступна або зараз недоречна.",
    notesEn: "Use this when barbell loading is not available or not appropriate.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "rear-foot-elevated-split-squat",
    nameEn: "Rear Foot Elevated Split Squat",
    category: "strength",
    combatProfiles: ["striker", "hybrid"],
    pattern: "squat",
    bodyRegions: ["lower", "hip", "knee"],
    equipment: ["Dumbbells", "Bodyweight"],
    level: "intermediate",
    phases: ["all"],
    defaultSets: "3",
    defaultReps: "6/side",
    defaultTempo: "3-1-X-1",
    defaultRest: "90s",
    defaultIntensity: "2 RIR",
    contraindications: ["Knee"],
    notesUa: "Тримай стопу і коліно стабільно.",
    notesEn: "Keep foot and knee stable.",
    sourceReference: "OTA-inspired",
  }),
  ex({
    id: "weighted-chin-up",
    nameEn: "Weighted Chin-Up",
    category: "strength",
    combatProfiles: ["grappler", "hybrid"],
    pattern: "pull",
    bodyRegions: ["upper", "grip"],
    equipment: ["Pull-up Bar"],
    level: "advanced",
    phases: ["accumulation", "transmutation"],
    defaultSets: "3",
    defaultReps: "4-6",
    defaultTempo: "2-1-X-1",
    defaultRest: "2 min",
    defaultIntensity: "RPE 7",
    contraindications: ["Elbow/Wrist/Hand", "Shoulder"],
    notesUa: "Сильна тяга, але не вбивай хват перед боротьбою.",
    notesEn: "Strong pull, but do not bury grip before wrestling.",
    sourceReference: "OTA-inspired",
  }),
  ex({
    id: "push-up",
    nameEn: "Push-Up",
    category: "strength",
    combatProfiles: ["striker", "grappler", "hybrid"],
    pattern: "push",
    bodyRegions: ["upper", "trunk"],
    equipment: ["Bodyweight", "Mat Only"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "3",
    defaultReps: "6-12",
    defaultTempo: "3-1-X-1",
    defaultRest: "75s",
    defaultIntensity: "2 RIR",
    contraindications: ["Shoulder", "Elbow/Wrist/Hand"],
    notesUa: "Ребра вниз, плече рухається чисто.",
    notesEn: "Keep ribs down and shoulder path clean.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "shoulder-isometric-reset",
    nameEn: "Shoulder Isometric Reset",
    category: "prehab",
    combatProfiles: ["striker", "hybrid", "grappler"],
    pattern: "isometric",
    bodyRegions: ["shoulder", "scap"],
    equipment: ["Bodyweight", "Bands"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "2",
    defaultReps: "20s/position",
    defaultTempo: "ISO",
    defaultRest: "30s",
    defaultIntensity: "Pain-free",
    notesUa: "Тільки без болю: легкий тиск, чиста позиція лопатки.",
    notesEn: "Pain-free only: light pressure, clean scapular position.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "landmine-press",
    nameEn: "Landmine Press",
    category: "strength",
    combatProfiles: ["striker", "hybrid"],
    pattern: "push",
    bodyRegions: ["shoulder", "trunk"],
    equipment: ["Barbell"],
    level: "intermediate",
    phases: ["all"],
    defaultSets: "3",
    defaultReps: "6/side",
    defaultTempo: "2-0-X-1",
    defaultRest: "90s",
    defaultIntensity: "RPE 7",
    contraindications: ["Shoulder"],
    notesUa: "Плече рухається чисто, ребра вниз.",
    notesEn: "Clean shoulder path, ribs down.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "farmer-carry",
    nameEn: "Farmer Carry",
    category: "accessory",
    combatProfiles: ["grappler", "hybrid"],
    pattern: "carry",
    bodyRegions: ["grip", "trunk", "shoulder"],
    equipment: ["Dumbbells", "Kettlebells"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "3",
    defaultReps: "30m",
    defaultTempo: "-",
    defaultRest: "90s",
    defaultIntensity: "Heavy but clean",
    contraindications: ["Elbow/Wrist/Hand", "Shoulder"],
    notesUa: "Хват і корпус, без перекосу.",
    notesEn: "Grip and trunk without leaning.",
    sourceReference: "Daru-inspired",
  }),
  ex({
    id: "pallof-press",
    nameEn: "Pallof Press",
    category: "accessory",
    combatProfiles: ["striker", "hybrid", "grappler"],
    pattern: "anti_rotation",
    bodyRegions: ["trunk"],
    equipment: ["Bands", "Cable"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "3",
    defaultReps: "10/side",
    defaultTempo: "2-1-2-1",
    defaultRest: "45s",
    defaultIntensity: "Smooth",
    notesUa: "Не крути корпус.",
    notesEn: "Do not rotate the trunk.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "sled-push",
    nameEn: "Sled Push",
    category: "accessory",
    combatProfiles: ["hybrid", "grappler"],
    pattern: "conditioning",
    bodyRegions: ["lower", "trunk"],
    equipment: ["Sled"],
    level: "intermediate",
    phases: ["all"],
    defaultSets: "3",
    defaultReps: "20m",
    defaultTempo: "-",
    defaultRest: "90s",
    defaultIntensity: "Hard",
    notesUa: "Потужно, але без відмови.",
    notesEn: "Powerful, but not to failure.",
    sourceReference: "Daru-inspired",
  }),
  ex({
    id: "zone-2-bike",
    nameEn: "Zone 2 Bike",
    category: "conditioning",
    combatProfiles: ["all"],
    pattern: "conditioning",
    bodyRegions: ["cardio"],
    equipment: ["Bike"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "1",
    defaultReps: "25-35 min",
    defaultTempo: "-",
    defaultRest: "-",
    defaultIntensity: "HR Zone 2",
    notesUa: "Ніс/легке дихання, без закислення.",
    notesEn: "Easy nasal or controlled breathing, no burn.",
    sourceReference: "Daru-inspired",
  }),
  ex({
    id: "assault-bike-repeated-efforts",
    nameEn: "Assault Bike Repeated Efforts",
    category: "conditioning",
    combatProfiles: ["grappler", "hybrid"],
    pattern: "conditioning",
    bodyRegions: ["cardio"],
    equipment: ["Bike"],
    level: "intermediate",
    phases: ["transmutation", "realization"],
    defaultSets: "6",
    defaultReps: "15s",
    defaultTempo: "-",
    defaultRest: "75s",
    defaultIntensity: "RPE 8",
    notesUa: "Імітація повторних вибухів без техніки боротьби.",
    notesEn: "Repeat bursts without adding grappling skill fatigue.",
    sourceReference: "Daru-inspired",
  }),
  ex({
    id: "tempo-runs-or-bike",
    nameEn: "Tempo Runs or Bike",
    category: "conditioning",
    combatProfiles: ["striker", "hybrid"],
    pattern: "conditioning",
    bodyRegions: ["cardio"],
    equipment: ["Open Space", "Bike", "Treadmill"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "8",
    defaultReps: "30s",
    defaultTempo: "-",
    defaultRest: "60s",
    defaultIntensity: "Zone 3-4",
    notesUa: "Ритм раунду, не максимум.",
    notesEn: "Round rhythm, not max effort.",
    sourceReference: "Daru-inspired",
  }),
  ex({
    id: "neck-isometric-series",
    nameEn: "Neck Isometric Series",
    category: "prehab",
    combatProfiles: ["grappler", "hybrid", "striker"],
    pattern: "isometric",
    bodyRegions: ["neck"],
    equipment: ["Bodyweight"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "2",
    defaultReps: "15s each",
    defaultTempo: "ISO",
    defaultRest: "30s",
    defaultIntensity: "Easy",
    contraindications: ["Neck", "Concussion History"],
    notesUa: "Без болю і без різких рухів.",
    notesEn: "No pain and no jerky motion.",
    sourceReference: "Daru-inspired",
  }),
  ex({
    id: "copenhagen-plank",
    nameEn: "Copenhagen Plank",
    category: "prehab",
    combatProfiles: ["grappler", "hybrid", "striker"],
    pattern: "isometric",
    bodyRegions: ["adductor", "hip", "knee"],
    equipment: ["Bench", "Mat Only"],
    level: "intermediate",
    phases: ["all"],
    defaultSets: "2",
    defaultReps: "20s/side",
    defaultTempo: "ISO",
    defaultRest: "45s",
    defaultIntensity: "Clean",
    contraindications: ["Hip", "Knee"],
    notesUa: "Профілактика паху/коліна.",
    notesEn: "Groin/knee prevention.",
    sourceReference: "Daru-inspired",
  }),
  ex({
    id: "calf-isometric-hold",
    nameEn: "Calf Isometric Hold",
    category: "prehab",
    combatProfiles: ["striker", "hybrid"],
    pattern: "isometric",
    bodyRegions: ["ankle", "calf"],
    equipment: ["Bodyweight"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "2",
    defaultReps: "30s",
    defaultTempo: "ISO",
    defaultRest: "45s",
    defaultIntensity: "Moderate",
    contraindications: ["Ankle/Foot"],
    notesUa: "Стопа жорстка, але без судоми.",
    notesEn: "Foot stiff, but no cramping.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "band-external-rotation",
    nameEn: "Band External Rotation",
    category: "prehab",
    combatProfiles: ["striker", "hybrid", "grappler"],
    pattern: "pull",
    bodyRegions: ["shoulder", "scap"],
    equipment: ["Bands"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "2",
    defaultReps: "12/side",
    defaultTempo: "2-1-2-1",
    defaultRest: "30s",
    defaultIntensity: "Easy",
    contraindications: ["Shoulder"],
    notesUa: "Лопатка стабільна.",
    notesEn: "Scapula stays stable.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "dead-bug",
    nameEn: "Dead Bug",
    category: "prehab",
    combatProfiles: ["hybrid", "striker", "grappler"],
    pattern: "anti_rotation",
    bodyRegions: ["trunk"],
    equipment: ["Mat Only"],
    level: "beginner",
    phases: ["all"],
    defaultSets: "2",
    defaultReps: "8/side",
    defaultTempo: "controlled",
    defaultRest: "30s",
    defaultIntensity: "Clean",
    notesUa: "Ребра вниз, таз стабільний.",
    notesEn: "Ribs down, pelvis stable.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "zercher-squat",
    nameEn: "Zercher Squat",
    category: "strength",
    combatProfiles: ["striker", "grappler", "hybrid"],
    pattern: "squat",
    bodyRegions: ["lower", "trunk", "upper back"],
    equipment: ["Barbell", "Squat Rack"],
    level: "intermediate",
    phases: ["accumulation", "transmutation"],
    contraindications: ["Lower Back", "Elbow/Wrist/Hand"],
    defaultSets: "3-4",
    defaultReps: "4-6",
    defaultTempo: "3-1-X-1",
    defaultRest: "2-3 min",
    defaultIntensity: "RPE 7-8",
    notesUa: "Притисни гриф у згинах ліктів, вдихни в пояс і сідай між стопами без округлення спини.",
    notesEn: "Pin the bar into the elbows, brace, and squat between the feet without rounding.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "belt-split-squat-isometric-overcoming",
    nameEn: "Belt Split Squat Overcoming Isometric",
    category: "strength",
    combatProfiles: ["striker", "grappler", "hybrid"],
    pattern: "isometric",
    bodyRegions: ["hip", "knee", "trunk"],
    equipment: ["Belt Squat", "Pins"],
    level: "advanced",
    phases: ["transmutation", "realization"],
    contraindications: ["Hip", "Knee", "Lower Back"],
    defaultSets: "3",
    defaultReps: "5-7s/side",
    defaultTempo: "ISO",
    defaultRest: "2 min",
    defaultIntensity: "Max intent",
    notesUa: "Зафіксуй бойову стійку й тисни тазом угору в нерухомий опір, не зсуваючи передню стопу.",
    notesEn: "Lock in the fight stance and drive into the fixed resistance without shifting the lead foot.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "rdl-isometric-hold",
    nameEn: "Romanian Deadlift Isometric Hold",
    category: "strength",
    combatProfiles: ["striker", "grappler", "hybrid"],
    pattern: "hinge",
    bodyRegions: ["posterior chain", "trunk", "grip"],
    equipment: ["Barbell"],
    level: "intermediate",
    phases: ["accumulation", "transmutation"],
    contraindications: ["Lower Back", "Hip"],
    defaultSets: "3",
    defaultReps: "6-8s",
    defaultTempo: "ISO",
    defaultRest: "2 min",
    defaultIntensity: "RPE 7",
    notesUa: "Відведи таз назад, зупини гриф нижче колін і тримай ребра над тазом без руху колін.",
    notesEn: "Hinge back, stop below the knees, and hold ribs over pelvis without changing knee angle.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "single-leg-ghr-eccentric",
    nameEn: "Single-Leg Glute-Ham Raise Eccentric",
    category: "accessory",
    combatProfiles: ["striker", "grappler", "hybrid"],
    pattern: "hinge",
    bodyRegions: ["posterior chain", "knee", "hip"],
    equipment: ["GHD"],
    level: "advanced",
    phases: ["accumulation", "transmutation"],
    contraindications: ["Knee", "Lower Back", "Hip"],
    defaultSets: "2-3",
    defaultReps: "3/side",
    defaultTempo: "5-0-X-0",
    defaultRest: "90s",
    defaultIntensity: "Assisted return",
    notesUa: "Зафіксуй таз на подушці й опускай пряму лінію плечі-таз повільно однією ногою; повертайся з допомогою.",
    notesEn: "Keep shoulders and hips aligned, lower on one leg, and use assistance to return.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "db-bench-isometric-hold",
    nameEn: "Dumbbell Bench Isometric Hold",
    category: "strength",
    combatProfiles: ["striker", "grappler", "hybrid"],
    pattern: "push",
    bodyRegions: ["upper", "shoulder", "trunk"],
    equipment: ["Dumbbells", "Bench"],
    level: "intermediate",
    phases: ["accumulation", "transmutation"],
    contraindications: ["Shoulder", "Elbow/Wrist/Hand"],
    defaultSets: "3",
    defaultReps: "5s + 3",
    defaultTempo: "ISO-X",
    defaultRest: "90s",
    defaultIntensity: "RPE 7",
    notesUa: "Зупини гантелі над нижньою точкою, тримай передпліччя вертикально й після паузи вичави без втрати ребер.",
    notesEn: "Hold just above the bottom with vertical forearms, then press without losing rib position.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "contralateral-band-row",
    nameEn: "Contralateral Single-Arm Band Row",
    category: "power",
    combatProfiles: ["striker", "grappler", "hybrid"],
    pattern: "pull",
    bodyRegions: ["upper", "trunk", "hip", "scap"],
    equipment: ["Bands"],
    level: "intermediate",
    phases: ["transmutation", "realization"],
    contraindications: ["Shoulder", "Elbow/Wrist/Hand"],
    defaultSets: "3",
    defaultReps: "5/side",
    defaultTempo: "X-0-2-0",
    defaultRest: "60s",
    defaultIntensity: "Fast",
    notesUa: "Постав протилежну ногу вперед, натягни стрічку до ребер і дозволь тазу передати силу без провертання коліна.",
    notesEn: "Set the opposite foot forward and row to the ribs through the hip without twisting the knee.",
    sourceReference: "Daru-inspired",
  }),
  ex({
    id: "wrist-pronation-supination-overcoming-isometric",
    nameEn: "Wrist Pronation-Supination Overcoming Isometric",
    category: "prehab",
    combatProfiles: ["striker", "grappler", "hybrid"],
    pattern: "isometric",
    bodyRegions: ["wrist", "forearm", "grip"],
    equipment: ["Fixed Bar", "Towel"],
    level: "intermediate",
    phases: ["all"],
    contraindications: ["Elbow/Wrist/Hand"],
    defaultSets: "2",
    defaultReps: "5s/direction",
    defaultTempo: "ISO",
    defaultRest: "45s",
    defaultIntensity: "Strong, pain-free",
    notesUa: "Тримай лікоть біля корпуса й намагайся повернути нерухомий хват долонею вниз та вгору без руху плеча.",
    notesEn: "Keep the elbow close and try to rotate the fixed grip without moving the shoulder.",
    sourceReference: "Daru-inspired",
  }),
  ex({
    id: "four-way-neck-yielding-isometric",
    nameEn: "Four-Way Neck Yielding Isometric",
    category: "prehab",
    combatProfiles: ["striker", "grappler", "hybrid"],
    pattern: "isometric",
    bodyRegions: ["neck", "upper back"],
    equipment: ["Bands", "Partner"],
    level: "intermediate",
    phases: ["all"],
    contraindications: ["Neck", "Concussion History"],
    defaultSets: "2",
    defaultReps: "8-12s/direction",
    defaultTempo: "ISO",
    defaultRest: "45s",
    defaultIntensity: "Submaximal, pain-free",
    notesUa: "Витягни потилицю, сховай підборіддя й утримуй голову нерухомо проти рівного тиску в чотирьох напрямках.",
    notesEn: "Lengthen the neck, tuck the chin, and resist smooth pressure in four directions.",
    sourceReference: "Daru-inspired",
  }),
  ex({
    id: "groin-bench-oscillatory",
    nameEn: "Groin Bench Oscillatory",
    category: "prehab",
    combatProfiles: ["striker", "grappler", "hybrid"],
    pattern: "isometric",
    bodyRegions: ["adductor", "hip", "trunk"],
    equipment: ["Bench", "Mat Only"],
    level: "advanced",
    phases: ["transmutation", "realization"],
    contraindications: ["Hip", "Knee"],
    defaultSets: "2",
    defaultReps: "10-15/side",
    defaultTempo: "quick, short range",
    defaultRest: "60s",
    defaultIntensity: "Crisp",
    notesUa: "Вирівняй плече-таз-коліно, тисни верхньою ногою в лаву й працюй у малому діапазоні без провисання таза.",
    notesEn: "Align shoulder, hip, and knee, then pulse through the top leg without dropping the pelvis.",
    sourceReference: "Daru-inspired",
  }),
  ex({
    id: "accelerated-band-ankle-hops",
    nameEn: "Accelerated Band Ankle Hops",
    category: "power",
    combatProfiles: ["striker", "hybrid"],
    pattern: "jump",
    bodyRegions: ["ankle", "calf", "lower"],
    equipment: ["Bands", "Open Space"],
    level: "advanced",
    phases: ["transmutation", "realization"],
    contraindications: ["Ankle/Foot", "Knee"],
    defaultSets: "3",
    defaultReps: "5-8",
    defaultTempo: "reactive",
    defaultRest: "75s",
    defaultIntensity: "Max stiffness",
    notesUa: "Тримай коліна м'якими, але майже нерухомими; відскакуй стопою швидко й припини, щойно контакт стає довгим.",
    notesEn: "Keep the knees soft but quiet, rebound through the foot, and stop when contact time grows.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "staggered-depth-jump",
    nameEn: "Staggered Depth Jump",
    category: "power",
    combatProfiles: ["striker", "grappler", "hybrid"],
    pattern: "jump",
    bodyRegions: ["lower", "ankle", "knee", "hip"],
    equipment: ["Box", "Open Space"],
    level: "advanced",
    phases: ["realization"],
    contraindications: ["Ankle/Foot", "Knee", "Lower Back"],
    defaultSets: "3-4",
    defaultReps: "2/stance",
    defaultTempo: "reactive",
    defaultRest: "2 min",
    defaultIntensity: "Max quality",
    notesUa: "Зійди з низької тумби, прийми зміщену стійку під центром мас і відразу вистрибни без завалу стопи чи коліна.",
    notesEn: "Step from a low box, receive a staggered stance under the center of mass, and rebound cleanly.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "standing-band-hip-flexor-oscillation",
    nameEn: "Standing Band Hip Flexor Oscillation",
    category: "accessory",
    combatProfiles: ["striker", "grappler", "hybrid"],
    pattern: "isometric",
    bodyRegions: ["hip", "trunk", "ankle"],
    equipment: ["Bands"],
    level: "intermediate",
    phases: ["transmutation", "realization"],
    contraindications: ["Hip", "Lower Back"],
    defaultSets: "2-3",
    defaultReps: "8-12/side",
    defaultTempo: "quick, short range",
    defaultRest: "60s",
    defaultIntensity: "Fast",
    notesUa: "Стій високо на опорній стопі, тримай таз рівно й швидко веди коліно вгору в малому діапазоні.",
    notesEn: "Stay tall over the stance foot, keep the pelvis level, and pulse the knee up quickly.",
    sourceReference: "Daru-inspired",
  }),
  ex({
    id: "ankle-rocker-single-leg-squat",
    nameEn: "Single-Leg Squat for Ankle Rocker",
    category: "mobility",
    combatProfiles: ["striker", "grappler", "hybrid"],
    pattern: "mobility",
    bodyRegions: ["ankle", "knee", "foot"],
    equipment: ["Bodyweight", "Wall"],
    level: "beginner",
    phases: ["all"],
    contraindications: ["Ankle/Foot", "Knee"],
    defaultSets: "2",
    defaultReps: "6/side",
    defaultTempo: "3-1-2",
    defaultRest: "30s",
    defaultIntensity: "Pain-free range",
    notesUa: "Тримай п'яту й великий палець на підлозі, веди коліно над другим пальцем і повертайся без завалу склепіння.",
    notesEn: "Keep heel and big toe down as the knee tracks over the second toe without arch collapse.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "90-90-hip-switch",
    nameEn: "90/90 Hip Switch",
    category: "mobility",
    combatProfiles: ["striker", "grappler", "hybrid"],
    pattern: "mobility",
    bodyRegions: ["hip"],
    equipment: ["Bodyweight", "Mat Only"],
    level: "beginner",
    phases: ["all"],
    contraindications: ["Hip", "Knee"],
    defaultSets: "2",
    defaultReps: "6/side",
    defaultTempo: "controlled",
    defaultRest: "30s",
    defaultIntensity: "Smooth",
    notesUa: "Посади обидва коліна під кутом близько 90°, обертай стегна разом і не відривай сідниці, якщо діапазон це дозволяє.",
    notesEn: "Set both knees near 90 degrees and rotate the hips together without lifting the seat.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "adductor-rock-back",
    nameEn: "Quadruped Adductor Rock-Back",
    category: "mobility",
    combatProfiles: ["striker", "grappler", "hybrid"],
    pattern: "mobility",
    bodyRegions: ["adductor", "hip"],
    equipment: ["Mat Only"],
    level: "beginner",
    phases: ["all"],
    contraindications: ["Hip", "Knee"],
    defaultSets: "2",
    defaultReps: "8/side",
    defaultTempo: "3-1-2",
    defaultRest: "30s",
    defaultIntensity: "Gentle tension",
    notesUa: "Відведи пряму ногу вбік, збережи стопу на підлозі й веди таз назад без обертання корпуса.",
    notesEn: "Extend one leg to the side and rock the hips back without rotating the trunk.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "quadruped-t-spine-rotation",
    nameEn: "Quadruped T-Spine Rotation",
    category: "mobility",
    combatProfiles: ["striker", "grappler", "hybrid"],
    pattern: "mobility",
    bodyRegions: ["t-spine", "shoulder"],
    equipment: ["Mat Only"],
    level: "beginner",
    phases: ["all"],
    contraindications: ["Shoulder", "Lower Back", "Neck"],
    defaultSets: "2",
    defaultReps: "6/side",
    defaultTempo: "controlled",
    defaultRest: "30s",
    defaultIntensity: "Pain-free range",
    notesUa: "Притисни опорну долоню, сядь тазом трохи назад і веди лікоть за поглядом, не обертаючи поперек.",
    notesEn: "Press through the support hand and follow the elbow with the eyes without turning the low back.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "shoulder-wall-slide",
    nameEn: "Shoulder Wall Slide",
    category: "mobility",
    combatProfiles: ["striker", "grappler", "hybrid"],
    pattern: "mobility",
    bodyRegions: ["shoulder", "scap", "t-spine"],
    equipment: ["Wall"],
    level: "beginner",
    phases: ["all"],
    contraindications: ["Shoulder", "Neck"],
    defaultSets: "2",
    defaultReps: "8",
    defaultTempo: "2-1-2",
    defaultRest: "30s",
    defaultIntensity: "Pain-free range",
    notesUa: "Легко тисни передпліччями в стіну, ковзай угору разом із лопатками й не випинай нижні ребра.",
    notesEn: "Press lightly into the wall and let the scapulae rise without flaring the lower ribs.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "scapular-push-up",
    nameEn: "Scapular Push-Up",
    category: "mobility",
    combatProfiles: ["striker", "grappler", "hybrid"],
    pattern: "mobility",
    bodyRegions: ["scap", "shoulder", "trunk"],
    equipment: ["Bodyweight", "Mat Only"],
    level: "beginner",
    phases: ["all"],
    contraindications: ["Shoulder", "Elbow/Wrist/Hand"],
    defaultSets: "2",
    defaultReps: "8-10",
    defaultTempo: "2-1-2",
    defaultRest: "30s",
    defaultIntensity: "Controlled",
    notesUa: "Залиши лікті прямими, дозволь грудній клітці опуститися між лопатками й потім відштовхни підлогу без округлення попереку.",
    notesEn: "Keep elbows straight, let the chest sink between the scapulae, then push the floor away.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "quadruped-wrist-rock",
    nameEn: "Quadruped Wrist Rock",
    category: "mobility",
    combatProfiles: ["striker", "grappler", "hybrid"],
    pattern: "mobility",
    bodyRegions: ["wrist", "forearm"],
    equipment: ["Mat Only"],
    level: "beginner",
    phases: ["all"],
    contraindications: ["Elbow/Wrist/Hand"],
    defaultSets: "2",
    defaultReps: "8",
    defaultTempo: "3-1-2",
    defaultRest: "30s",
    defaultIntensity: "Gentle tension",
    notesUa: "Розкрий пальці, притисни всю долоню й перенось плечі вперед лише до межі, де кисть не стискається й не болить.",
    notesEn: "Spread the fingers, keep the whole palm down, and rock only through a pain-free wrist range.",
    sourceReference: "Black Bear",
  }),
  ex({
    id: "neck-controlled-rotation",
    nameEn: "Controlled Neck Rotation",
    category: "mobility",
    combatProfiles: ["striker", "grappler", "hybrid"],
    pattern: "mobility",
    bodyRegions: ["neck"],
    equipment: ["Bodyweight"],
    level: "beginner",
    phases: ["all"],
    contraindications: ["Neck", "Concussion History"],
    defaultSets: "1-2",
    defaultReps: "4/side",
    defaultTempo: "slow",
    defaultRest: "30s",
    defaultIntensity: "Pain-free range",
    notesUa: "Витягни потилицю, тримай підборіддя рівно й повертай голову повільно без нахилу та без проходу крізь біль.",
    notesEn: "Lengthen the neck and rotate slowly without tilting or moving through pain.",
    sourceReference: "Black Bear",
  }),
];

export function findExercise(id: string) {
  const exercise = exerciseLibrary.find((item) => item.id === id);
  if (!exercise) throw new Error(`Missing exercise: ${id}`);
  return exercise;
}

export function prescribeExercise(
  id: string,
  overrides: Partial<Pick<ExerciseLibraryItem, "defaultSets" | "defaultReps" | "defaultTempo" | "defaultRest" | "defaultIntensity">> = {},
) {
  const exercise = findExercise(id);
  const evidence = getRuleEvidence(["bbp.exercise.selection"]);
  return {
    name: exercise.nameEn,
    sets: overrides.defaultSets ?? exercise.defaultSets,
    reps: overrides.defaultReps ?? exercise.defaultReps,
    tempo: overrides.defaultTempo ?? exercise.defaultTempo,
    rest: overrides.defaultRest ?? exercise.defaultRest,
    intensity: overrides.defaultIntensity ?? exercise.defaultIntensity,
    notesUa: exercise.notesUa,
    notesEn: exercise.notesEn,
    legacySourceReference: exercise.sourceReference,
    ...evidence,
    methodologySupport: "unsupported" as const,
  };
}

export function prescribeBestExercise(
  ids: string[],
  athleteProfile: AthleteProfile,
  overrides: Partial<Pick<ExerciseLibraryItem, "defaultSets" | "defaultReps" | "defaultTempo" | "defaultRest" | "defaultIntensity">> = {},
) {
  const preferred = ids.map(findExercise);
  const available = preferred.filter((exercise) => isExerciseAvailable(exercise, athleteProfile));
  const safeAvailable = available.filter((exercise) => !hasRiskConflict(exercise, athleteProfile));
  const selected = safeAvailable[0] ?? available[0] ?? preferred[0];
  const prescription = prescribeExercise(selected.id, overrides);
  const conflicts = getRiskConflicts(selected, athleteProfile);

  if (conflicts.length) {
    const warningUa = `Ризик: ${conflicts.join(", ")}. Працюй тільки без болю, зменши амплітуду або заміни вправу.`;
    const warningEn = `Risk flag: ${conflicts.join(", ")}. Keep it pain-free, reduce range, or replace the exercise.`;
    return {
      ...prescription,
      notesUa: [prescription.notesUa, warningUa].filter(Boolean).join(" "),
      notesEn: [prescription.notesEn, warningEn].filter(Boolean).join(" "),
    };
  }

  return prescription;
}

export function filterExercises(category: ExerciseCategory, profile: CombatProfile) {
  return exerciseLibrary.filter(
    (exercise) => exercise.category === category && (exercise.combatProfiles.includes(profile) || exercise.combatProfiles.includes("all")),
  );
}

function isExerciseAvailable(exercise: ExerciseLibraryItem, athleteProfile: AthleteProfile) {
  const alwaysAvailable = ["Bodyweight", "Mat Only", "Open Space"];
  const availableEquipment = new Set([...alwaysAvailable, ...athleteProfile.equipment]);
  return exercise.equipment.some((item) => availableEquipment.has(item));
}

function hasRiskConflict(exercise: ExerciseLibraryItem, athleteProfile: AthleteProfile) {
  return getRiskConflicts(exercise, athleteProfile).length > 0;
}

function getRiskConflicts(exercise: ExerciseLibraryItem, athleteProfile: AthleteProfile) {
  const risks = new Set(athleteProfile.painAreas);
  return exercise.contraindications.filter((risk) => risks.has(risk));
}

function ex(item: ExerciseLibraryInput): ExerciseLibraryItem {
  return {
    contraindications: [],
    ...item,
  };
}
